trigger:
  branches:
    include:
    - develop
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Npm@1
      inputs:
        command: install
      displayName: 'npm install'
    - task: CopyFiles@2
      inputs:
        contents: 'dist/**'
        TargetFolder: 'temp'
    - task: CopyFiles@2
      inputs:
        contents: 'node_modules/**'
        TargetFolder: 'temp'
    - task: CopyFiles@2
      inputs:
        contents: 'package.json'
        TargetFolder: 'temp'
    - task: CopyFiles@2
      inputs:
        contents: 'web.config'
        TargetFolder: 'temp'
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: 'temp'
        includeRootFolder: false
    - task: SynopsysDetectTask@6
      inputs:
        BlackDuckService: 'blackduck1'
        DetectVersion: 'latest'