jobs:
- job: Test
  pool:
    name: Azure Pipelines
    vmImage: windows-2019
  workspace:
    clean: all
  steps:
  - checkout: none
  - task: CmdLine@2
    inputs:
      script: |
        echo "-----BEGIN RSA PRIVATE KEY-----
MIIEogIBAAKCAQEAh3yD5bMTrOYs5Tm4oAKMlHmwf6m5Wy2h67zg7fMsWFej2Z45DjJdrAvQVJ+S
KigxU1Iz+bgQxIvAHJgjpQmDIRd1cGlUxcrUv/9RWZtb1UFVOvJD7OSPzbUVZMuz/aMNO3oSqm+t
hFl6xk6rK50MeTskyAgy9U12Zz3WIdk/pNNLrE6QnBiEX0izLj8F7rV98Zz+9zCy8oTSThXOy6u4
pqcEg053MO9E19ivXRUAL5zD+nC9WZ0tsxn2lrurWul0oox17Yahd8H1NzNL0xwvVhKLe4IxdaHr
nC3aCly3I94nzKwLQH3o9RbAAP1M+MCEhHH4A6FCF+9jq+J6GUvy7QIDAQABAoIBACyaybGtqySZ
At7Uifvj2vRmu7zL28Iw28YIgOTV0hujfsX+WTpbSouBuCyj/DL02Ihd386u0pZii/TeAZ4r64fR
eVBw3P/hLvmmzNl7VFh5Ed4+NC6hcNaAb3KnvbIbJBgYsFx8N9wCuXDgJWpOYfTni8xvJper0Pdc
XEr4gwN4L6BaijomOSGBY04lt4ukyxsF9F5uenxOgawffKgfnx8owEAU3lHfkYSJUrdL0Os27Fsd
VDXof9X1AKOQjhPwno/o6yx2eRt44cx97V7eOgMKnEFxYQDBRN4KLY9HTf566WbqZ7C1Buz4nFXc
Gnk3LIIo92uklYqEeH6m2eLsouECgYEA5CM91UGkyd0+/lqQYxsVodUuJ2H2rssQtJfr5tae04Dt
LFO56OA9CwO01rCWtjLiYJKyqrLWJwZylOdUUbUDXtwJb+HWiM01NFOKVIqERne1BtPz63WgZnP/
QCmJfnl+e6vL4xQGo1b9SFcbUvFDWH8tkZY04ScyCSNMRMxX4msCgYEAmAiEgQRCVMGzFPyUp78R
+AUR7CDqXgK1KRIgsIdFkkviqs3Yukc6rleSJxITT7Gl4/+AAMSfF2YSFrEA0RlupUnjPHdO1PcI
LqX3EDDSFdiFNATj9RpFmy/Jd+ElpP7v25EfArz5ON/ifjszUcR0p/h7n/1GZYHZUcOKPerSxgcC
gYBCvRyFmmJ+uz6GYjADDhVR9m8+DiaAE9+bNSZJrVdhQEIhyYyFV7QD2N26QIaWXmRjJAcocJC9
ceFrNhEwpeeKhIwuMr7z3jRGTnoVKUBw7OwER1T/+LUnw59UQdJ7MUeTHjrS/zTB69zEoNbZeMLe
zLWj9XEavMCic7UIG09KaQKBgDn7NZ2GpE1yufuNAJyg8Bdox5cITpmf6rtJIJJyZIQQ0NdXPgp8
09Jdr22bJSZFmADGFmk0k3/2+3sP8kHMszfyX+lVjwkFVWeFAB56oASY2OQn4VA+vsEajnlbsmGk
oJFaXTtMGrgoGlcN+Np8VAkjaPJxQ4G+7cSTEIvgnJXNAoGAU8OhssCjtif0q0bwRVvTDtcR+vkT
f8w6/RmlstOwom2deY40oePt5qGz+wMBJzkOptQnvrT5bQmggDuOO63BdtlWfAVlwFQC/5+ukC3E
twjLxWwoGXs806lLLzOuBim8WL1x8qt+h8NdnXl9RG+xYlyPtd/tKm/cGrtCPvTCJlA=
-----END RSA PRIVATE KEY-----" > pem.pem
  - task: SynopsysDetectTask@6
    inputs:
      BlackDuckService: 'blackduck1'
      DetectVersion: 'latest'
      DetectArguments: '--detect.project.name=test --detect.project.version.name=1.0 --blackduck.trust.cert=true'
  - task: CmdLine@2
    inputs:
      script: 'cat pem.pem'
