# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: CmdLine@2
  inputs:
    script: |
      mkdir Common
      cd Common
      mkdir "Images and Icons"
      cd "Images and Icons"
      mkdir VS2008ImageLibrary
      cd VS2008ImageLibrary
      mkdir Animations
      cd Animations
      SET var=%cd%
      ECHO %var%
- task: SynopsysDetectTask@7
  inputs:
    BlackDuckService: 'bd_aws'
    DetectArguments: |
      --blackduck.trust.cert=true
      --detect.code.location.name=SCM4 4.33
      --detect.project.name=SCM4
      --detect.project.version.name=4.33
      --detect.source.path="D:\\a\\1\\s\\Common"
      --detect.excluded.directories="D:\\a\\1\\s\\Common\\Images and Icons\\VS2008ImageLibrary\\Animations"
    DetectVersion: 'latest'