jobs:
- job: Test
  pool:
    name: Azure Pipelines
    vmImage: windows-2019
  workspace:
    clean: all
  steps:
  - checkout: none
  - task: SynopsysDetectTask@6
    inputs:
      BlackDuckService: 'blackduck1'
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: 'set DETECT_LATEST_RELEASE_VERSION=6.7.0'
      DetectArguments: '--blackduck.trust.cert=true'