jobs:
- job: Test
  pool:
    name: Azure Pipelines
    vmImage: windows-2019
  workspace:
    clean: all
  steps:
  - checkout: none
  - task: Bash@3
    name: bash1
    inputs:
      targetType: 'inline'
      script: 'curl -s -L https://detect.synopsys.com/detect.sh'
  - task: Bash@3
    name: bash2
    inputs:
      targetType: 'inline'
      script: 'bash <(curl -s -L https://detect.synopsys.com/detect.sh)'