# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-18.04

steps:
- task: CmdLine@2
  inputs:
    script: |
      mkdir s
      mkdir s/Common
      mkdir s/special
      mkdir s/Common/test
      pwd s/Common
- task: SynopsysDetectTask@7
  inputs:
    BlackDuckService: 'bd_aws'
    DetectArguments: |
      --blackduck.trust.cert=true
      --detect.bom.aggregate.name=SCM4 4.33
      --detect.cleanup=false
      --detect.code.location.name=SCM4 4.33
      --detect.project.name=SCM4
      --detect.project.version.name=4.33
      --detect.source.path=/home/vsts/work/1/s
      --detect.timeout=300
      --detect.excluded.directories=/home/vsts/work/1/s/special
    DetectVersion: 'latest'