trigger:
  branches:
    include:
    - develop
pool:
  vmImage: 'ubuntu-latest'

steps:
    - task: SynopsysDetectTask@6
      inputs:
        BlackDuckService: 'blackduck1'
        DetectVersion: 'latest'
