jobs:
- job: Test
  pool:
    name: Azure Pipelines
    vmImage: windows-2019
  workspace:
    clean: all
  steps:
  - checkout: none
  - task: SynopsysPolaris@1
    inputs:
      polarisService: 'polaris3'
      polarisCommand: 'analyze -w'