trigger:
  branches:
    include:
    - develop
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: SynopsysDetectTask@9
      inputs:
        BlackDuckService: 'blackduck1'
        DetectVersion: 'latest'
        DetectArguments: '--detect.timeout=300 --detect.project.name=Hello World'