jobs:
- job: Test
  pool:
    name: Azure Pipelines
    vmImage: windows-2019
  variables:
    DETECT_LATEST_RELEASE_VERSION: 6.7.0
  workspace:
    clean: all
  steps:
  - checkout: none
  - task: SynopsysDetectTask@6
    inputs:
      BlackDuckService: 'blackduck1'
      DetectArguments: '--blackduck.trust.cert=true'