trigger:
  branches:
    include:
    - develop
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: SynopsysDetectTask@6
      inputs:
        BlackDuckService: 'Blackduck_Hub'
        DetectVersion: 'latest'
