# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-18.04

steps:
- 
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      mkdir /home/detect/
      wget --no-check-certificate https://sig-repo.synopsys.com/artifactory/bds-integrations-release/com/synopsys/integration/synopsys-detect/6.9.1/synopsys-detect-6.9.1-air-gap.zip -O /home/detect/detect.zip
      unzip /home/detect/detect.zip

