jobs:
- job: Test
  pool:
    name: Azure Pipelines
    vmImage: windows-2019
  workspace:
    clean: all
  steps:
  - checkout: none
  - task: Bash@3
    name: bash2
    inputs:
      targetType: 'inline'
      script: '
      env ;
      echo "++++++++++++++++++++++" ;
      bash <(curl -s -L https://detect.synopsys.com/detect.sh) --blackduck.url=https://ec2-54-92-223-129.compute-1.amazonaws.com --blackduck.api.token=YWFlOTVkMzUtYTQ1OC00NTNkLWI2ZTUtMmZiNDE1NzNmMDk3OjczMTg2MzdjLTgxNjMtNGFlMy04YTUzLWY0ZTQxNzcxZjI0OQ== --blackduck.trust.cert=true --detect.project.name=NWCC_ALL --detect.project.version.name=NWCC_Q121';
      export proxy http_proxy="http://1.1.1.1:8080";
      export proxy https_proxy="https://1.1.1.1:8080";
      bash <(curl -s -L https://detect.synopsys.com/detect.sh) --blackduck.url=https://ec2-54-92-223-129.compute-1.amazonaws.com --blackduck.api.token=YWFlOTVkMzUtYTQ1OC00NTNkLWI2ZTUtMmZiNDE1NzNmMDk3OjczMTg2MzdjLTgxNjMtNGFlMy04YTUzLWY0ZTQxNzcxZjI0OQ== --blackduck.trust.cert=true --detect.project.name=NWCC_ALL --detect.project.version.name=NWCC_Q121';
