jobs:
- job: Test
  pool:
    name: Azure Pipelines
    vmImage: windows-2019
  workspace:
    clean: all
  steps:
  - checkout: none

- task: CmdLine@2
  inputs:
    script: 'bash <(curl -s -L https://detect.synopsys.com/detect.sh) --blackduck.url=https://ec2-3-239-34-0.compute-1.amazonaws.com --blackduck.api.token=ZjE4YWQxZWYtYTM4My00ZjExLWJlMzctNmI1YjIwM2QwMDQ2OjVmNDMwNjA2LWE0ZTktNDQ4NS1iYTExLWVkOWJhNWI0M2E5OA== --blackduck.trust.cert=true --detect.project.name=project1 --detect.project.version.name=version1'
    inputs:
      BlackDuckService: 'blackduck1'
      DetectVersion: 'latest'
      DetectArguments: '--blackduck.trust.cert=true --logging.level.com.synopsys.integration=TRACE'