# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    ping bbc.co.uk
    ping cegid.app.blackduck.com
    ping asml.app.blackduck.com
  displayName: 'Run a multi-line script'
