jobs:
- job: Test
  pool:
    name: Azure Pipelines
    vmImage: windows-2019
  workspace:
    clean: all
  steps:
  - checkout: none
- task: SynopsysDetectTask@3
  inputs:
    BlackDuckService: 'blackduck1'
    DetectVersion: 'latest'
    DetectArguments: '--blackduck.trust.cert=true'