jobs:
- job: Test
  pool:
    name: Azure Pipelines
    vmImage: windows-2019
  workspace:
    clean: all
  steps:
  - checkout: none
  - task: CmdLine@2
    inputs:
      script: |
        echo "-----BEGIN RSA PRIVATE KEY-----MIIEogIBAAKCAQEAh3yD5bMTrOYs5Tm4oAKMlHmwf6m5Wy2h67zg7fMsWFej2Z45DjJdrAvQVJ+SKigxU1Iz+bgQxIvAHJgjpQmDIRd1cGlUxcrUv/9RWZtb1UFVOvJD7OSPzbUVZMuz/aMNO3oSqm+thFl6xk6rK50MeTskyAgy9U12Zz3WIdk/pNNLrE6QnBiEX0izLj8F7rV98Zz+9zCy8oTSThXOy6u4pqcEg053MO9E19ivXRUAL5zD+nC9WZ0tsxn2lrurWul0oox17Yahd8H1NzNL0xwvVhKLe4IxdaHrnC3aCly3I94nzKwLQH3o9RbAAP1M+MCEhHH4A6FCF+9jq+J6GUvy7QIDAQABAoIBACyaybGtqySZAt7Uifvj2vRmu7zL28Iw28YIgOTV0hujfsX+WTpbSouBuCyj/DL02Ihd386u0pZii/TeAZ4r64fReVBw3P/hLvmmzNl7VFh5Ed4+NC6hcNaAb3KnvbIbJBgYsFx8N9wCuXDgJWpOYfTni8xvJper0PdcXEr4gwN4L6BaijomOSGBY04lt4ukyxsF9F5uenxOgawffKgfnx8owEAU3lHfkYSJUrdL0Os27FsdVDXof9X1AKOQjhPwno/o6yx2eRt44cx97V7eOgMKnEFxYQDBRN4KLY9HTf566WbqZ7C1Buz4nFXcGnk3LIIo92uklYqEeH6m2eLsouECgYEA5CM91UGkyd0+/lqQYxsVodUuJ2H2rssQtJfr5tae04DtLFO56OA9CwO01rCWtjLiYJKyqrLWJwZylOdUUbUDXtwJb+HWiM01NFOKVIqERne1BtPz63WgZnP/QCmJfnl+e6vL4xQGo1b9SFcbUvFDWH8tkZY04ScyCSNMRMxX4msCgYEAmAiEgQRCVMGzFPyUp78R+AUR7CDqXgK1KRIgsIdFkkviqs3Yukc6rleSJxITT7Gl4/+AAMSfF2YSFrEA0RlupUnjPHdO1PcILqX3EDDSFdiFNATj9RpFmy/Jd+ElpP7v25EfArz5ON/ifjszUcR0p/h7n/1GZYHZUcOKPerSxgcCgYBCvRyFmmJ+uz6GYjADDhVR9m8+DiaAE9+bNSZJrVdhQEIhyYyFV7QD2N26QIaWXmRjJAcocJC9ceFrNhEwpeeKhIwuMr7z3jRGTnoVKUBw7OwER1T/+LUnw59UQdJ7MUeTHjrS/zTB69zEoNbZeMLezLWj9XEavMCic7UIG09KaQKBgDn7NZ2GpE1yufuNAJyg8Bdox5cITpmf6rtJIJJyZIQQ0NdXPgp809Jdr22bJSZFmADGFmk0k3/2+3sP8kHMszfyX+lVjwkFVWeFAB56oASY2OQn4VA+vsEajnlbsmGkoJFaXTtMGrgoGlcN+Np8VAkjaPJxQ4G+7cSTEIvgnJXNAoGAU8OhssCjtif0q0bwRVvTDtcR+vkTf8w6/RmlstOwom2deY40oePt5qGz+wMBJzkOptQnvrT5bQmggDuOO63BdtlWfAVlwFQC/5+ukC3EtwjLxWwoGXs806lLLzOuBim8WL1x8qt+h8NdnXl9RG+xYlyPtd/tKm/cGrtCPvTCJlA=-----END RSA PRIVATE KEY-----" > pem.pem
  - task: SynopsysDetectTask@6
    inputs:
      BlackDuckService: 'blackduck1'
      DetectVersion: 'latest'
      DetectArguments: '--detect.project.name=test --detect.project.version.name=1.0 --blackduck.trust.cert=true'
  - task: CmdLine@2
    inputs:
      script: 'ssh -i pem.pem -t ec2-user@ec2-3-90-44-94.compute-1.amazonaws.com "sudo mkdir /tmp/test"'
